<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{b1f6439c-46b6-4383-84e4-595b760f4386}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[M3SelectorA();
M3SelectorB();
M3SelectorC();
M3SelectorD();
PCMA();
PCMB();
PCMC();
PCMD();
GasMan();
BronkhorstA();
BronkhorstB();
BronkhorstC();
BronkhorstD();
SolenoidPairA();

(* Following execution of all the programs, set the first pass false *)
g_xFirstPass := FALSE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>